- Gemfile
- Gemfile.lock
- Procfile
- README.md
- app.rb
The app doesn't use the web process, but I think it was there because
the old, free dyno structure didn't allow for workers without a web
process. Production is now on a Professional worker dyno with no web
dyno, and staging is on a hobby worker dyno with no web dyno. It seems
like bumping up to any of the free tiers removes the web process
restriction and we can now get rid of it.
> Remove Sinatra and the web process

- lib/ext/scss_lint/config.rb
- lib/jobs/scss_review_job.rb
- spec/jobs/scss_review_job_spec.rb
Why:
* `scss-lint` assumes files are stored on a disk,
and it expands paths before matching them for exclusion checks.
* Hound doesn't store files to disk,
thus we have to make an assumption about the root path.
* This fixes a current issue where SCSS files aren't excluded.
Fixes https://github.com/thoughtbot/hound/issues/879
> Monkey patch SCSS-Lint to match excluded files

- Gemfile
- Gemfile.lock
- config/default.yml
- lib/jobs/scss_review_job.rb
- spec/jobs/scss_review_job_spec.rb
Changes:
- Use a tempfile instead of the raw content.
`scss-lint` removed support for linting the content of a file, and now
only lints actual files.
To remedy that fact, we create a tempfile with the content of the file the
service is linting.
- Upgrade scss-lint's default configuration.
- Tweak the config to have the same opinionated defaults as before.
- Allow all new rules.
- Remove severity level
https://trello.com/c/tltqHIJ6
> Upgrade `scss_lint`

- Gemfile
- Gemfile.lock
- config/default.yml
- lib/jobs/scss_review_job.rb
I pulled the configuration straight from SCSS-Lint’s, found here: https://github.com/brigade/scss-lint/blob/master/config/default.yml
> Update SCSS-Lint to v0.43.2

- lib/config_options.rb
- lib/jobs/report_invalid_config_job.rb
- lib/jobs/scss_review_job.rb
- spec/config_options_spec.rb
- spec/jobs/scss_review_job_spec.rb
When an invalid configuration file is parsed, it should be marked as
invalid to let the end user know.
This is done by enqueuing the `ReportInvalidConfigJob` in Hound proper,
which will update the build status to mark the configuration file as
invalid.
https://trello.com/c/42U5K0Bs
> Report invalid configuration files in Hound proper

- lib/jobs/scss_review_job.rb
- lib/review.rb
- spec/config_options_spec.rb
- spec/jobs/scss_review_job_spec.rb
- spec/review_spec.rb
- spec/spec_helper.rb
- spec/support/strip_heredoc.rb
This removes the attempts to create OO in `ScssReviewJob` with its
`private_class_method`'s.
Changes:
- Extract all strings into constants, and freeze them. For memory
purposes.
> Extract service object out of `ScssReviewJob`

- README.md
In response to the https://github.com/thoughtbot/hound/issues/736 and
https://github.com/thoughtbot/hound/pull/1046#issuecomment-176995767
Providing a link to the description of all the specific options in the
SCSS config should make it easier to understand what each specified
option does.
> Add link to the SCSS configuration options

- lib/haml_lint/violation.rb
- spec/lib/haml_lint/runner_spec.rb
- spec/lib/haml_lint/violation_spec.rb
When haml-lint reports an error, e.g. invalid syntax, it does not
include a rule name in the message. The regex for parsing these messages
is assuming a rule name will be present and is failing to capture error
messages because of it.
Additionally, when reporting errors, haml-lint seems to use zero-based
indexing.
This commit:
* Updates `HamlLint::Violation` regex pattern to have an optional rule
name, so errors are matched
* Updates `HamlLint::Violation#line_number` to increment the line number
by one when the message is an error, so the correct line number is
reported
Related: https://github.com/houndci/hound/pull/1112
> Report haml-lint errors as violations

- lib/scss_lint/violation.rb
- spec/lib/scss_lint/runner_spec.rb
- spec/lib/scss_lint/violation_spec.rb
scss-lint's rule names can sometimes include a space, e.g. "Syntax
Error". The regex for parsing scss-lint output is assuming rule names to
contain no whitespace and is failing to capture some errors because of
it.
This updates the `ScssLint::Violation` regex pattern to allow spaces in
rule names.
https://trello.com/c/95xQa6Xr
> Report scss-lint errors as violations

- lib/haml_lint/violation.rb
- lib/jobs/haml_review_job.rb
- lib/jobs/scss_review_job.rb
- lib/linters/haml_lint.rb
- lib/linters/scss_lint.rb
- lib/runner.rb
- lib/scss_lint.rb
- lib/scss_lint/violation.rb
- spec/jobs/scss_review_job_spec.rb
- spec/lib/haml_lint/violation_spec.rb
- spec/lib/linters/haml_lint_spec.rb
- spec/lib/linters/scss_lint_spec.rb
- spec/lib/scss_lint/violation_spec.rb
* Extracts commonalities from `ScssReviewJob` and `HamlReviewJob` into a
new `Runner` class
* Introduces `Linters` top level namespace
* Moves `HamlLint::Runner` to `Linters::HamlLint`
* Moves `ScssLint::Runner` to `Linters::ScssLint`
* Moves `HamlLint::Violation` to `Haml::Violation` to avoid the
`HamlLint` namespace collision. The `Haml` namespace will be removed
in a future commit.
* Moves `ScssLint::Violation` to `Scss::Violation` to avoid the
`ScssLint` namespace collision. The `Scss` namespace will be removed
in a future commit.
https://trello.com/c/tNkpUewT
> Extract common code from review jobs

- .gitignore
- Procfile
- config/eslintrc
- jobs/eslint_review_job.rb
- lib/linters/eslint/options.rb
- lib/linters/eslint/tokenizer.rb
- package.json
- spec/jobs/eslint_review_job_spec.rb
This is using a ruby wrapper for ESLint.
This will not ignore files natively, since ignore file isn't sent as
part of the job payload.
Hound proper handles ignoring JS files, and does not schedule jobs if
files are ignored. So, we are okay for now.
At some point we might want to consider supporting native file ignores,
but then we'll be scheduling jobs for files that are simply ignored.
> Add ESLint

- lib/linters/eslint/options.rb
- lib/linters/haml_lint/options.rb
- lib/linters/runner.rb
- lib/linters/scss_lint/options.rb
- spec/jobs/eslint_review_job_spec.rb
ESLint by default lints only .js extensions.
Let's ensure the linter lints the file + filename in the review process.
> Lint specific filename

- lib/linters/eslint/tokenizer.rb
- lib/linters/jshint/tokenizer.rb
- lib/linters/runner.rb
- lib/linters/scss_lint/tokenizer.rb
- lib/linters/tokenizer.rb
There was quite a bit of duplication for parsing violation output in
most tokenizers. I extracted this into a higher-level `Tokenizer` class.
> Extract common output parsing logic into a class

- config/rubocop.yml
- spec/jobs/rubocop_review_job_spec.rb
- spec/support/helpers/linters_helper.rb
Otherwise, RuboCop will assume an oldest supported Ruby version if it's
not specified by the user. From their docs:
```
What MRI version of the Ruby interpreter is the inspected code intended
to run on? (If there is more than one, set this to the lowest version.)
If a value is specified for TargetRubyVersion then it is used.
Else if .ruby-version exists and it contains an MRI version it is used.
Otherwise we fallback to the oldest officially supported Ruby version
(2.0).
```
Thus, we should either default it to `2.3`, or tell users that get
strange "token" (code parse) errors to specify `TargetRubyVersion` in
their custom config.
> Set default Ruby version for RuboCop

- lib/linters/config.rb
- spec/jobs/rubocop_review_job_spec.rb
- spec/lib/linters/config_spec.rb
In RuboCop's case, we'll lose the default `TargetRubyVersion` config
if custom config file contains `AllCops` key.
For example, a custom config like:
```yaml
AllCops:
Exclude:
- 'specs/helpers/**/*'
```
Will revert to using the lowest supported `TargetRubyVersion` because
our current merge strategy only merges top-level keys, thus causing the
final config to be `{"AllCops"=>{"Exclude"=>["specs/helpers/**/*"]}}`.
> Deep merge configs

- lib/linters/coffeelint/options.rb
- spec/jobs/coffeelint_review_job_spec.rb
Updates `Coffeelint::Options` to replace ERB tags in the file with the
value `123`. This is to keep feature parity with the previous linter,
removed in https://github.com/houndci/hound/pull/1206
https://trello.com/c/pj5BdqFU
> Support ERB in CoffeeScript

- lib/linters/coffeelint/tokenizer.rb
- spec/jobs/coffeelint_review_job_spec.rb
The `#` character beings a comment line in Ruby regex, when
in `x` (whitespace ignore) mode.
Thus, it needs be escaped to be considered part of the regex.
Also, optionally ignore code syntax errors, that show up in the form of:
```
✗ #11: [stdin]:11:1: error: unexpected indentation
```
> Escape hashtag character in CoffeeLint regex

- package.json
Updated ESLint version to [v3.7.1](http://eslint.org/blog/2016/10/eslint-v3.7.1-released).
Particularly, [v3.6.0](http://eslint.org/blog/2016/09/eslint-v3.6.0-released) is an important change because it includes partial support for ES2017, which introduces some new syntax (e.g. `async` `await`).
Anyway, thank you for the great software! I love Hound ❤️
> Update eslint to v3.7.1

- lib/linters/credo/tokenizer.rb
- spec/lib/linters/credo/tokenizer_spec.rb
The regex was incorrectly parsing the column number instead of the line number.
This updates the regex and adds a test from a real world example to protect this
from coming up again in the future.
> Fix Credo line number parsing

- lib/linters/base/options.rb
- lib/linters/coffeelint/options.rb
- lib/linters/credo/options.rb
- lib/linters/eslint/options.rb
- lib/linters/haml_lint/options.rb
- lib/linters/jshint/options.rb
- lib/linters/rubocop/options.rb
- lib/linters/scss_lint/options.rb
- lib/linters/tslint/options.rb
- spec/lib/linters/base/options_spec.rb
The options classes across all linters behave similarly, but can vary
here and there. Because there is no real comprehensive documentation of
these objects -- what they do, what they accept, what they return --
there is some friction when attempting to create a new linter and the
associated objects.
This commit holds a base abstract Options class that acts as a contract
for the `Options` classes that need implementing. Raising
NotImplementedError clearly dictates what methods are needed. The Yarddoc
style method annotations communicate what it is that they should do.
> Create abstract base options class w/annotations

- Gemfile
- Gemfile.lock
- README.md
- bin/resque
- jobs/reek_review_job.rb
- lib/linters/reek/options.rb
- lib/linters/reek/tokenizer.rb
- spec/jobs/reek_review_job_spec.rb
- spec/lib/linters/reek/tokenizer_spec.rb
"Linter" in quotes as it is a code **_quality_** tool, not style adherence per se.
Reek will tell you where in your project you have potential code smells. The code smell detection it provides is listen on their project page: https://github.com/troessner/reek/blob/master/docs/Code-Smells.md
This pull request is an initial attempt at getting Reek into Hound. Comments and questions forthcoming in the commits' code.
> Add reek code smell tool as a "linter"

- Gemfile
- Gemfile.lock
- bin/resque
- lib/jobs/flog_review_job.rb
- lib/linters/flog/options.rb
- lib/linters/flog/tokenizer.rb
- spec/jobs/flog_review_job_spec.rb
- spec/lib/linters/flog/tokenizer_spec.rb
Before, we only checked Ruby files using Rubocop. This only allowed us to comment on the style of the files. Added a Flog integration which will comment on Ruby methods that are too complex.
> Set Hound up to Flog Ruby changes

- package.json
Addresses: https://github.com/houndci/hound/issues/1309
This PR allows your `.eslintrc` to select `babel-eslint` or `esprima` as alternative eslint parsers to `espree`.
I'm not certain that `babel` isn't also required because it's not listed as a dependency in babel-eslint, but I left it out.
> Add babel-eslint and esprima modules so eslint can select either as parsers

- lib/linters/reek/options.rb
- lib/linters/reek/tokenizer.rb
- spec/jobs/reek_review_job_spec.rb
- spec/lib/linters/reek/tokenizer_spec.rb
When reek finds a code smell it will provide a link to the project's
wiki where an explanation for that code smell is. There is further
information about what it's "smelling", how it may be configured (on or
off) and what it's checking for.
This commit/PR provides that link, but formatted with markdown in order to
reduce noise in the comment.
> Add link to code smell explanation

- .gitignore
- bin/resque
- jobs/linters_job.rb
- spec/jobs/linters_job_spec.rb
- spec/support/helpers/linters_helper.rb
Our `QUEUE` situation is getting a bit large.
We only need one queue, since we pass the `linter_name` in the payload.
The idea is to slowly move Hound main app, to use this queue -- maybe
start with new linters first.
> Use one job queue

- lib/linters/command_result.rb
- lib/linters/lint.rb
- lib/linters/runner.rb
- lib/linters/system_call.rb
- spec/lib/linters/command_result_spec.rb
- spec/lib/linters/runner_spec.rb
- spec/lib/linters/system_call_spec.rb
- spec/support/helpers/linters_helper.rb
Various linters don't adhere to one strict methodology on when to return
`0` or `1` or `2` as exit codes.
For example, RuboCop returns `1` when there are violations and `2` when
any other problem is encountered. However, JSHint uses `2` when
violations are found/reported.
So, instead if there is output, but no violations could be parsed, we
can assume that something else went wrong and thus report that output as
an error.
> Report shelled out command errors

- package.json
- yarn.lock
This comes with all react applications created with `create-react-app`
(the de-facto standard way).
> Add eslint-config-react-app ESLint plugin

- lib/linters/config.rb
RuboCop config can now contain serialized symbols in its YAML.
> Whitelist serialized symbols when parsing YAML

- lib/linters/runner.rb
- spec/lib/linters/runner_spec.rb
In the case of ESLint, we are seeing a recursive stack-trace error for a
certain situation. This makes the error output very long and causes us
to send this back and store it on Hound's end. In turn, GitHub limits
the review body comment to 64KB which this error output can go over.
> Report only unique error output lines

- lib/linters/runner.rb
- spec/lib/linters/runner_spec.rb
Some linters will print out the filename of the config file when they
encounter an error with its contents. Since we write the config file
(and run the linters) from a temp path, the output can be sometimes
confusing. Let's strip out the temp path and just report the filename.
The test handles both unix (Heroku) and OSX temp paths.
> Strip out temp path from error outputs

- spec/lib/linters/runner_spec.rb
The test was passing because the linter was erroring due to `Enabled`
not being indented properly. It also happened to detect wrong namespace
for `Style/AlignHash`. This wasn't quite the intention of the test.
Thus, I've clarified it by adding another rule that actually causes the
linter to exit with non-zero status, and now test against the exact/full
error output.
> Fix the test for linter error case

- package.json
- yarn.lock
This PR adds the `eslint-plugin-compat`. This plugin will lint javascript functions you call that are not supported by the browsers you support. You just declare your browser support and the linter plugin will pick it up.
> Add eslint-plugin-compat to package.json

- lib/linters/credo/options.rb
- spec/jobs/credo_review_job_spec.rb
- yarn.lock
Credo will try to evaluate `config_import` line and look for the file
that is being imported (e.g. `config/prod.exs`). Since Hound lints one
file at a time, that file to-be-imported will not befound and cause
Credo to error, like:
```
** (Mix.Config.LoadError) could not load config config/prod.exs
** (File.Error) could not read file "config/prod.exs": no such file or directory
(elixir) lib/file.ex:244: File.read!/1
(mix) lib/mix/config.ex:180: Mix.Config.read!/2
(mix) lib/mix/config.ex:217: anonymous fn/3 in Mix.Config.read_wildcard!/2
(elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
(stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
(stdlib) erl_eval.erl:404: :erl_eval.expr/5
```
Stripping those lines from the file before …
> Strip config_import lines for Credo/Elixir

- .yarnrc
Yarn 1.0+ started erroring if engine versions (e.g. Node) doesn't match
the one specified in the `package.json` vs installed locally.
It can be quite annoying to update `package.json` everytime node is
updated locally. Plus, different folks are not likely to be on the
latest node version.
We could remove this later, if mismatched Node versions start to cause
issues.
> Ignore Node version mismatch when using Yarn

- .tool-versions
- runtime.txt
Heroku wants 3.6.2 now and won't run with 3.6.1.
> Upgrade Python to 3.6.2
